CREATE TABLE IF NOT EXISTS swap_data_rune_pool_meta (
    id SERIAL PRIMARY KEY,
    start_time NUMERIC(39, 0) NOT NULL,
    end_time NUMERIC(39, 0) NOT NULL,
    to_asset_count NUMERIC(39, 0) NOT NULL,
    to_rune_count NUMERIC(39, 0) NOT NULL,
    to_trade_count NUMERIC(39, 0) NOT NULL,
    from_trade_count NUMERIC(39, 0) NOT NULL,
    synth_mint_count NUMERIC(39, 0) NOT NULL,
    synth_redeem_count NUMERIC(39, 0) NOT NULL,
    total_count NUMERIC(39, 0) NOT NULL,
    to_asset_volume NUMERIC(39, 0) NOT NULL,
    to_rune_volume NUMERIC(39, 0) NOT NULL,
    to_trade_volume NUMERIC(39, 0) NOT NULL,
    from_trade_volume NUMERIC(39, 0) NOT NULL,
    synth_mint_volume NUMERIC(39, 0) NOT NULL,
    synth_redeem_volume NUMERIC(39, 0) NOT NULL,
    total_volume NUMERIC(39, 0) NOT NULL,
    to_asset_volume_usd NUMERIC(39, 0) NOT NULL,
    to_rune_volume_usd NUMERIC(39, 0) NOT NULL,
    to_trade_volume_usd NUMERIC(39, 0) NOT NULL,
    from_trade_volume_usd NUMERIC(39, 0) NOT NULL,
    synth_mint_volume_usd NUMERIC(39, 0) NOT NULL,
    synth_redeem_volume_usd NUMERIC(39, 0) NOT NULL,
    total_volume_usd NUMERIC(39, 0) NOT NULL,
    to_asset_fees NUMERIC(39, 0) NOT NULL,
    to_rune_fees NUMERIC(39, 0) NOT NULL,
    to_trade_fees NUMERIC(39, 0) NOT NULL,
    from_trade_fees NUMERIC(39, 0) NOT NULL,
    synth_mint_fees NUMERIC(39, 0) NOT NULL,
    synth_redeem_fees NUMERIC(39, 0) NOT NULL,
    total_fees NUMERIC(39, 0) NOT NULL,
    to_asset_average_slip DOUBLE PRECISION NOT NULL,
    to_rune_average_slip DOUBLE PRECISION NOT NULL,
    to_trade_average_slip DOUBLE PRECISION NOT NULL,
    from_trade_average_slip DOUBLE PRECISION NOT NULL,
    synth_mint_average_slip DOUBLE PRECISION NOT NULL,
    synth_redeem_average_slip DOUBLE PRECISION NOT NULL,
    average_slip DOUBLE PRECISION NOT NULL,
    rune_price_usd DOUBLE PRECISION NOT NULL
);

CREATE TABLE IF NOT EXISTS swap_data_rune_pool_interval (
    id SERIAL PRIMARY KEY,
    start_time NUMERIC(39, 0) NOT NULL,
    end_time NUMERIC(39, 0) NOT NULL,
    to_asset_count NUMERIC(39, 0) NOT NULL,
    to_rune_count NUMERIC(39, 0) NOT NULL,
    to_trade_count NUMERIC(39, 0) NOT NULL,
    from_trade_count NUMERIC(39, 0) NOT NULL,
    synth_mint_count NUMERIC(39, 0) NOT NULL,
    synth_redeem_count NUMERIC(39, 0) NOT NULL,
    total_count NUMERIC(39, 0) NOT NULL,
    to_asset_volume NUMERIC(39, 0) NOT NULL,
    to_rune_volume NUMERIC(39, 0) NOT NULL,
    to_trade_volume NUMERIC(39, 0) NOT NULL,
    from_trade_volume NUMERIC(39, 0) NOT NULL,
    synth_mint_volume NUMERIC(39, 0) NOT NULL,
    synth_redeem_volume NUMERIC(39, 0) NOT NULL,
    total_volume NUMERIC(39, 0) NOT NULL,
    to_asset_average_slip DOUBLE PRECISION NOT NULL,
    to_rune_average_slip DOUBLE PRECISION NOT NULL,
    average_slip DOUBLE PRECISION NOT NULL,
    rune_price_usd DOUBLE PRECISION NOT NULL
);
